# Generated by Django 3.1 on 2020-09-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20200907_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.tweets'),
        ),
    ]
